#!/bin/bash
# longest-word3: find longest string in a file

for i; do
  if [[ -r "$1" ]]; then
    max_word=
    max_len=0
    for  in $(strings "$1"); do
      len="${#j}"
      if (( len > max_len )); then
        max_len="$len"
        max_word="$j"
      fi
    done
    echo "$1: '$max_word' ($max_len characters)"
  fi
done
