#!/bin/bash -x

# tracing_by_portion: script to demonstrate common errors

number=1

set -x # Turn on tracing
if [ $number = 1 ]; then
	echo "Number is equal to 1."
else
	echo "Number is not equal to 1."
fi

set +x # Turn on tracing
