#!/bin/bash

# Program to output a system information page

echo "<html>"
echo "	<head>"
echo "		<title>Page Title</title>"
echo "	</head>"
echo "	<body>"
echo "		Page body."
echo "	</body>"
echo "</html>"
